/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ncsu.monopoly.gui;

import edu.ncsu.monopoly.DataBase;
import edu.ncsu.monopoly.GameBoard;
import edu.ncsu.monopoly.GameMaster;
import edu.ncsu.monopoly.Player;
import edu.ncsu.monopoly.User;
import edu.ncsu.monopoly.test.boardScenarios.GameBoardFull;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class MainMenu extends javax.swing.JFrame {

    private DataBase dB;
    private WelcomeMenu previous;
    private ArrayList<Player> players;
    private ArrayList<JComboBox> comboBoxesColor;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(DataBase dBs, WelcomeMenu prev) {
        comboBoxesColor = new ArrayList<JComboBox>();
        players = new ArrayList<Player>();
        previous = prev;

        dB = dBs;
        initComponents();
        jCheckBoxUser1.setEnabled(false);

        jComboBoxUser2.setEnabled(false);
        // jTextField2.setEnabled(false);
        jComboBoxUser3.setEnabled(false);
        //jTextField3.setEnabled(false);
        jComboBoxUser4.setEnabled(false);
        //jTextField4.setEnabled(false);
        jComboBoxUser8.setEnabled(false);
        //jTextField8.setEnabled(false);
        jComboBoxUser7.setEnabled(false);
        //jTextField7.setEnabled(false);
        jComboBoxUser6.setEnabled(false);
        //jTextField5.setEnabled(false);
        jComboBoxUser5.setEnabled(false);
        //jTextField6.setEnabled(false);
        comboBoxesColor.add(jComboBoxColor1);
        comboBoxesColor.add(jComboBoxColor2);
        comboBoxesColor.add(jComboBoxColor3);
        comboBoxesColor.add(jComboBoxColor4);
        comboBoxesColor.add(jComboBoxColor5);
        comboBoxesColor.add(jComboBoxColor6);
        comboBoxesColor.add(jComboBoxColor7);
        comboBoxesColor.add(jComboBoxColor8);
        String[] colors = {"Green", "Orange", "Red", "Violet", "Yellow", "Gray", "Blue", "Black"};

        for (int i = 0; i < comboBoxesColor.size(); i++) {
            if (i > 0) {
                comboBoxesColor.get(i).setEnabled(false);
            }
            for (int j = 0; j < colors.length; j++) {
                comboBoxesColor.get(i).addItem(colors[j]);
            }
        }

        for (int i = 0; i < dB.getUsers().size(); i++) {

            jComboBoxUser1.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser2.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser3.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser4.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser5.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser6.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser7.addItem(dB.getUsers().get(i).getName());
            jComboBoxUser8.addItem(dB.getUsers().get(i).getName());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUser1 = new javax.swing.JComboBox<>();
        jLabelChoose = new javax.swing.JLabel();
        jCheckBoxUser1 = new javax.swing.JCheckBox();
        jCheckBoxUser2 = new javax.swing.JCheckBox();
        jComboBoxUser2 = new javax.swing.JComboBox<>();
        jCheckBoxUser3 = new javax.swing.JCheckBox();
        jComboBoxUser3 = new javax.swing.JComboBox<>();
        jComboBoxUser4 = new javax.swing.JComboBox<>();
        jCheckBoxUser4 = new javax.swing.JCheckBox();
        jCheckBoxUser8 = new javax.swing.JCheckBox();
        jCheckBoxUser7 = new javax.swing.JCheckBox();
        jCheckBoxUser6 = new javax.swing.JCheckBox();
        jCheckBoxUser5 = new javax.swing.JCheckBox();
        jComboBoxUser8 = new javax.swing.JComboBox<>();
        jComboBoxUser7 = new javax.swing.JComboBox<>();
        jComboBoxUser6 = new javax.swing.JComboBox<>();
        jComboBoxUser5 = new javax.swing.JComboBox<>();
        jButtonStart = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jComboBoxColor1 = new javax.swing.JComboBox<>();
        jComboBoxColor2 = new javax.swing.JComboBox<>();
        jComboBoxColor3 = new javax.swing.JComboBox<>();
        jComboBoxColor4 = new javax.swing.JComboBox<>();
        jComboBoxColor5 = new javax.swing.JComboBox<>();
        jComboBoxColor6 = new javax.swing.JComboBox<>();
        jComboBoxColor7 = new javax.swing.JComboBox<>();
        jComboBoxColor8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PredefPic/monopolyIlustration.jpg"))); // NOI18N

        jComboBoxUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser1ActionPerformed(evt);
            }
        });

        jLabelChoose.setText("Selecciona un usuario:");

        jCheckBoxUser1.setSelected(true);
        jCheckBoxUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser1ActionPerformed(evt);
            }
        });

        jCheckBoxUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser2ActionPerformed(evt);
            }
        });

        jComboBoxUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser2ActionPerformed(evt);
            }
        });

        jCheckBoxUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser3ActionPerformed(evt);
            }
        });

        jComboBoxUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser3ActionPerformed(evt);
            }
        });

        jComboBoxUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser4ActionPerformed(evt);
            }
        });

        jCheckBoxUser4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser4ActionPerformed(evt);
            }
        });

        jCheckBoxUser8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser8ActionPerformed(evt);
            }
        });

        jCheckBoxUser7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser7ActionPerformed(evt);
            }
        });

        jCheckBoxUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser6ActionPerformed(evt);
            }
        });

        jCheckBoxUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUser5ActionPerformed(evt);
            }
        });

        jComboBoxUser8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser8ActionPerformed(evt);
            }
        });

        jComboBoxUser7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser7ActionPerformed(evt);
            }
        });

        jComboBoxUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser6ActionPerformed(evt);
            }
        });

        jComboBoxUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUser5ActionPerformed(evt);
            }
        });

        jButtonStart.setText("Comenzar");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxUser8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelChoose)
                                    .addComponent(jComboBoxUser1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxUser7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxUser1)
                                    .addComponent(jCheckBoxUser2)
                                    .addComponent(jCheckBoxUser3)
                                    .addComponent(jCheckBoxUser4)
                                    .addComponent(jCheckBoxUser5)
                                    .addComponent(jCheckBoxUser6)
                                    .addComponent(jCheckBoxUser7)
                                    .addComponent(jCheckBoxUser8))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStart)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelChoose)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser1)
                            .addComponent(jComboBoxColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser2)
                            .addComponent(jComboBoxColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser3)
                            .addComponent(jComboBoxColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser4)
                            .addComponent(jComboBoxColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser5)
                            .addComponent(jComboBoxColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser6)
                            .addComponent(jComboBoxColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxUser7)
                            .addComponent(jComboBoxUser7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxUser8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxUser8)
                            .addComponent(jComboBoxColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        User guest = new User();
        guest.setName("Jugar como invitado");
        boolean isNoneSelected1 = ((String) jComboBoxUser1.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected2 = ((String) jComboBoxUser2.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected3 = ((String) jComboBoxUser3.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected4 = ((String) jComboBoxUser4.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected5 = ((String) jComboBoxUser5.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected6 = ((String) jComboBoxUser6.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected7 = ((String) jComboBoxUser7.getSelectedItem()).equals(guest.getName());
        boolean isNoneSelected8 = ((String) jComboBoxUser8.getSelectedItem()).equals(guest.getName());
        //boolean isNoneSelected = isNoneSelected1 || isNoneSelected2 || isNoneSelected3 || isNoneSelected4 || isNoneSelected5 || isNoneSelected6 || isNoneSelected7 || isNoneSelected8;
        boolean[] repeated = new boolean[9];
        ArrayList<String> chosenColors = new ArrayList<String>();
        int choseColorIndex = 0;
        boolean[] repeatedColors = new boolean[9];
        ArrayList<User> actualUsers = new ArrayList<User>();
        int i = 1;
        String actualName = "";
        ArrayList<String> names = new ArrayList<String>();
        if (!((String) jComboBoxUser1.getSelectedItem()).equals(guest.getName())) {

            names.add((String) jComboBoxUser1.getSelectedItem());
            User ui = dB.getUser((String) jComboBoxUser1.getSelectedItem());
            actualUsers.add(ui);

        } else {
            names.add("Invitado" + i);
            i++;
            User ui = null;
            actualUsers.add(ui);

        }
        chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
        choseColorIndex++;
        if (jCheckBoxUser2.isSelected()) {
            if (!((String) jComboBoxUser2.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser2.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser2.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser3.isSelected()) {
            if (!((String) jComboBoxUser3.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser3.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser3.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser4.isSelected()) {
            if (!((String) jComboBoxUser4.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser4.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser4.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser5.isSelected()) {
            if (!((String) jComboBoxUser5.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser5.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser5.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser6.isSelected()) {
            if (!((String) jComboBoxUser6.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser6.getSelectedItem();
                User ui = dB.getUser((String) jComboBoxUser6.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user

            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser7.isSelected()) {
            if (!((String) jComboBoxUser7.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser7.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser7.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;
        }

        if (jCheckBoxUser8.isSelected()) {
            if (!((String) jComboBoxUser8.getSelectedItem()).equals(guest.getName())) {
                actualName = (String) jComboBoxUser8.getSelectedItem();

                User ui = dB.getUser((String) jComboBoxUser8.getSelectedItem());
                actualUsers.add(ui);
                //create player2 as user
            } else {
                actualName = "Invitado" + i;
                i++;

                User ui = null;
                actualUsers.add(ui);
                //create player2 as guest
            }
            if (names.contains(actualName) && !actualName.equals("Invitado" + (i - 1))) {
                repeated[names.size()] = true;
            }
            names.add(actualName);
            if (chosenColors.contains((String) comboBoxesColor.get(choseColorIndex).getSelectedItem())) {
                repeatedColors[names.size()] = true;
            }
            chosenColors.add((String) comboBoxesColor.get(choseColorIndex).getSelectedItem());
            choseColorIndex++;

        }

        boolean hasRepetitions = false;

        String fstErrorMessage = "El/Los jugadores: ";
        String sndErrorMessage = " están quieren elegir usuarios ya elegidos";
        for (int j = 1; j < 9; j++) {
            if (repeated[j]) {
                if (hasRepetitions) {
                    fstErrorMessage += ", ";
                }
                fstErrorMessage += j + 1;
                hasRepetitions = true;
            }
        }

        if (hasRepetitions) {
            JOptionPane.showMessageDialog(this, fstErrorMessage + sndErrorMessage, "Error", WIDTH);
        }

        boolean colorsAreRepeated = false;
        String fstColorErrorMessage = "The player(s): ";
        String sndColorErrorMessage = " are choosing repeated colors";
        for (int j = 0; j < 9; j++) {
            if (repeatedColors[j]) {
                if (colorsAreRepeated) {
                    fstColorErrorMessage += ", ";
                }
                fstColorErrorMessage += j;
                colorsAreRepeated = true;
            }
        }
        if (colorsAreRepeated) {
            JOptionPane.showMessageDialog(this, fstColorErrorMessage + sndColorErrorMessage, "Error", WIDTH);
        }
        if (!hasRepetitions && !colorsAreRepeated) {
            GameMaster master = GameMaster.instance();
            MainWindow window = new MainWindow();
            GameBoard gameBoard = new GameBoardFull();

            master.setGameBoard(gameBoard);
            GameMaster.instance().setNumberOfPlayers(names.size());

            for (int j = 0; j < names.size(); j++) {
                Player pi = GameMaster.instance().getPlayer(j);
                if (actualUsers.get(j) != null) {
                    pi.setBelongsToUser(actualUsers.get(j));
                }
                pi.setName(names.get(j));
                pi.setColor(chosenColors.get(j));

            }
            window.setupGameBoard(gameBoard);
            window.show();
            master.setGUI(window);
            master.startGame();
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jComboBoxUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser5ActionPerformed

    }//GEN-LAST:event_jComboBoxUser5ActionPerformed

    private void jComboBoxUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser6ActionPerformed

    }//GEN-LAST:event_jComboBoxUser6ActionPerformed

    private void jComboBoxUser7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser7ActionPerformed

    }//GEN-LAST:event_jComboBoxUser7ActionPerformed

    private void jComboBoxUser8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser8ActionPerformed

    }//GEN-LAST:event_jComboBoxUser8ActionPerformed

    private void jCheckBoxUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser5ActionPerformed
        boolean isEnable = jCheckBoxUser5.isSelected();
        jComboBoxUser5.setEnabled(isEnable);
        comboBoxesColor.get(4).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser5ActionPerformed

    private void jCheckBoxUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser6ActionPerformed
        boolean isEnable = jCheckBoxUser6.isSelected();
        jComboBoxUser6.setEnabled(isEnable);
        comboBoxesColor.get(5).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser6ActionPerformed

    private void jCheckBoxUser7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser7ActionPerformed
        boolean isEnable = jCheckBoxUser7.isSelected();
        jComboBoxUser7.setEnabled(isEnable);
        comboBoxesColor.get(6).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser7ActionPerformed

    private void jCheckBoxUser8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser8ActionPerformed
        boolean isEnable = jCheckBoxUser8.isSelected();
        jComboBoxUser8.setEnabled(isEnable);
        comboBoxesColor.get(7).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser8ActionPerformed

    private void jCheckBoxUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser4ActionPerformed
        boolean isEnable = jCheckBoxUser4.isSelected();
        jComboBoxUser4.setEnabled(isEnable);
        comboBoxesColor.get(3).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser4ActionPerformed

    private void jComboBoxUser4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser4ActionPerformed

    }//GEN-LAST:event_jComboBoxUser4ActionPerformed

    private void jComboBoxUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser3ActionPerformed

    }//GEN-LAST:event_jComboBoxUser3ActionPerformed

    private void jCheckBoxUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser3ActionPerformed
        boolean isEnable = jCheckBoxUser3.isSelected();
        jComboBoxUser3.setEnabled(isEnable);
        comboBoxesColor.get(2).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser3ActionPerformed

    private void jComboBoxUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser2ActionPerformed

    }//GEN-LAST:event_jComboBoxUser2ActionPerformed

    private void jCheckBoxUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser2ActionPerformed
        boolean isEnable = jCheckBoxUser2.isSelected();
        jComboBoxUser2.setEnabled(isEnable);
        comboBoxesColor.get(1).setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser2ActionPerformed

    private void jCheckBoxUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUser1ActionPerformed
        boolean isEnable = jCheckBoxUser1.isSelected();
        jComboBoxUser1.setEnabled(isEnable);

    }//GEN-LAST:event_jCheckBoxUser1ActionPerformed

    private void jComboBoxUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUser1ActionPerformed

    }//GEN-LAST:event_jComboBoxUser1ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        previous.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBox jCheckBoxUser1;
    private javax.swing.JCheckBox jCheckBoxUser2;
    private javax.swing.JCheckBox jCheckBoxUser3;
    private javax.swing.JCheckBox jCheckBoxUser4;
    private javax.swing.JCheckBox jCheckBoxUser5;
    private javax.swing.JCheckBox jCheckBoxUser6;
    private javax.swing.JCheckBox jCheckBoxUser7;
    private javax.swing.JCheckBox jCheckBoxUser8;
    private javax.swing.JComboBox<String> jComboBoxColor1;
    private javax.swing.JComboBox<String> jComboBoxColor2;
    private javax.swing.JComboBox<String> jComboBoxColor3;
    private javax.swing.JComboBox<String> jComboBoxColor4;
    private javax.swing.JComboBox<String> jComboBoxColor5;
    private javax.swing.JComboBox<String> jComboBoxColor6;
    private javax.swing.JComboBox<String> jComboBoxColor7;
    private javax.swing.JComboBox<String> jComboBoxColor8;
    private javax.swing.JComboBox<String> jComboBoxUser1;
    private javax.swing.JComboBox<String> jComboBoxUser2;
    private javax.swing.JComboBox<String> jComboBoxUser3;
    private javax.swing.JComboBox<String> jComboBoxUser4;
    private javax.swing.JComboBox<String> jComboBoxUser5;
    private javax.swing.JComboBox<String> jComboBoxUser6;
    private javax.swing.JComboBox<String> jComboBoxUser7;
    private javax.swing.JComboBox<String> jComboBoxUser8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChoose;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
